
# Configurations for building ssh connections
rsa_file: 'ssh_needs/id_rsa'
known_hosts_file: 'ssh_needs/known_hosts'

# PlanetLab specific configuration
PLC_CREDENTIALS: 'ssh_needs/credentials.private'
slice_name: 'budapestple_cloud'
API_URL: 'https://www.planet-lab.eu:443/PLCAPI/'

repo_root: "planet-lab_dev"

# Research project specific configurations
ping_destination:
  ip: "152.66.247.138"
  username: "rudolf"
  password: "planetlab"

mptcp_measurements:
  target1: "152.66.244.82"
  target2: "152.66.127.81"
  target_username: "mptcp"
